language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

before_install:
  - pip install coveralls

install:
  - pip install Django==$_DJANGO
  - pip install -e .
  - pip install -r requirements.txt

script: make coverage

env:
  - _DJANGO=1.8.14
  - _DJANGO=1.9.8

matrix:
  exclude:
    - python: 3.3
      env: _DJANGO=1.9.8

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: change
